### ISSUE TITLE
Partial replacement of new pages

### ISSUE THREAD

**Issue by dhh** [rails/turbolinks#448]
Some great ideas from https://github.com/Shopify/turbograft that we should migrate into Turbolinks. The first is partial replacement. I was initially skeptical to this idea, but have been won over by seeing how it can really work well with permanent elements of a page like shopping carts or sidebars or other pieces with state. 

The big win from Turbolinks remain that the initial hit will generate the full page, and that you won't have to tailor server-side rendering on subsequent requests, even when you're only doing partial updates.

I'd like to propose the following API:

```
<div data-turbolinks-partial="section-a">
</div>

<div data-turbolinks-permanent>
</div>

<a href="#" data-turbolinks-change="section-a"></a>

Turbolinks.visit(url, change: [ 'section-a', 'section-b' ])
Turbolinks.visit(url, keep: [ 'section-c', 'section-d' ])
```

So you can name a partial with data-turbolinks-partial. These named partials can then be referred to in the Turbolinks.visit call through the change/keep options.

Marking an element with "data-turbolinks-permanent" will mean that it is not updated by any Turbolinks.visit call, except if you ALSO give the same element a partial name AND name that partial as part of a Turbolinks.visit/change call.

**Comment by kristianpd** [comment]
@dhh interesting to see this discussion taking place. A few comments:


## keep and change vs. refresh-always, refresh-never and refresh

`data-turbolinks-permanent` seems equivalent to our [refresh-never](https://github.com/Shopify/turbograft/blob/master/lib/assets/javascripts/turbograft/turbolinks.coffee#L139) key.  We only use this twice in our code base to prevent a `script` tag from executing inline more than once (tracking script). We never really ended up using it as much as we had thought we would. I'm curious what use cases you may have for putting it on an element like a `div`. I also intended for it to be used this way, but we never did.  

Though we only have a [`change` key](https://github.com/Shopify/turbograft/blob/master/lib/assets/javascripts/turbograft/turbolinks.coffee#L150), you also propose a `keep` key which is interesting. `keep` is sort of the inverse of our [`refresh-always` option](https://github.com/Shopify/turbograft/blob/master/lib/assets/javascripts/turbograft/turbolinks.coffee#L146) that you opt in to from the caller as opposed to making that decision in the DOM. We use `refresh-always` as a way of forcing a section to always be up to date and not needing the caller to worry about including it in their list of sections they wish to refresh. This allows our JS to focus more on performing some kind of data manipulation (POST requests are a big part of our approach) and then refresh anything that cares about that data. This is why we try to keep our `refresh` keys more descriptive of the data that affects them like "order" or "customer" instead of "section-orders-details" style keys.  

Rouging out a few examples:

```html+erb
<h1>Dashboard</h1>
<nav data-turbolinks-change="sidebar">
  <a data-turbolinks-change="order-count">Orders <%= @open_order_count %></a>
</nav>

<h1 data-turbolinks-change="order-count">You have <%= @open_order_count %> orders that need your attention.</h1>
<%= link_to "Update your account to have more features", onclick="Turbolinks.visit(url, change: ['sidebar'])" %>

<!-- option 1 -->
<%= link_to "Capture and fulfill all orders", onclick="Turbolinks.visit(url, keep: ['sidebar'])" %>

<!-- option 2 -->
<%= link_to "Capture and fulfill all orders", onclick="Turbolinks.visit(url, change: ['order-count'])" %>
```

## GET vs. POST

A good chunk of Turbograft's design is driven by the fact that you'll be mutating data and then refreshing one or many sections of the page as a result of that change. Turbolinks is different in that it's purely for a faster UX on GET's. For this reason, I'm curious what flow you see the `Turbolinks.visit` call with `change` or `keep` being used in? 

- Is it for when someone performs an AJAX request and then wants to refresh a section of the page they know changed? 
- Is it more to avoid refreshing sections (`data-turbolinks-permanent`) that will never change? 
- Would it be used in conjunction with `remote=true` calls to refresh a page after some form of persisting action took place?


## change keys can be greedy

In the example above, if you wanted to display an open order count in your sidebar nav, anytime you change the outer key `sidebar` you will affect any keys within it (at least in our implementation). That's not a problem in this case, but it does raise the question of what you do if you have a `data-turbolinks-permanent` node inside a node with a `change` key. This hasn't caused us any real pain yet, but there have been a few cases where we avoided putting keys on a wrapping node, and became more selective on the child nodes instead because of this. 

## we try to think of our keys as what-data-changes and not what-sections-change

Since Turbolinks is more GET than POST, I actually may prefer the `section-a` example of keys if you're thinking of using this more for higher-level layout control than for reflecting data changes in the UI. If however, it's being done more for refreshing sections after mutative calls have taken place, we try to keep our refresh keys more descriptive of the data that changes.

Of note, most of our pages only have 1 or 2 unique change keys on them, with additional `refresh-always` (sorta like a `data-turbolinks-ephemeral`) keys on our pages. We also rarely call `visit` with more than one `change` key.

## a rough thought on partials

A long long time ago, we had the idea that one day we may be able to hook in to rails partials to have speedier page rendering if we introduced the concept of refresh/section keys at a server level. We haven't done this, performance hasn't been an issue and it's probably an over optimization for us however I'm curious what your thoughts are on it playing more with Turbolinks. 

The idea was basically

**layouts/application.html.erb**
```html+erb
  <%= render 'main_nav', data-turbolinks-change="user_account" %>

  <%= yield %>
```

**views/foos/index.html.erb**
```html+erb
  <%= render 'foo_table' data-turbolink-change="foos" %>
  <%= render 'bar_table' data-turbolink-change="bars" %>
```

```javascript
Turbolinks.visit(url, change: ['foos'])
```

If rails would somehow acknowlege (HTTP headers?) change keys, we could make `render` aware of our partial rendering strategy and simply skip rendering any partials that don't share a key we care about. This was an early idea on how we could cut down on the size of response body but also has a few challenges (like greedy keys mentioned above) that we chose to never overcome. It also proved to not be a performance issue to render an entire layout + body in the back buffer even if we only needed a section or two.

Haven't really thought about this idea in a while, but this PR sparked it again.



Interested in seeing where this goes!

**Comment by kristianpd** [comment]
:+1:.

One restriction we added to partial replacement nodes is they need an ID as well as the key so we can find the corresponding note in the replacement DOM. There's also a few cases like "what if the node goes away or is created" that need to be handled. Sort of like a poor mans React diff.

I'll try to find a little time this week to open a PR with some partial replacement prototyping.

**Comment by dhh** [comment]
Why can't you find the nodes via ('[data-turbolinks-section=X]')?

And yeah, this def is similar in many ways to the React stuff. Hopefully we can get away with far less complexity.

**Comment by kristianpd** [comment]
The `('[data-turbolinks-section=x]')` selector will only returns nodes that are "watching" that section. As soon as you have multiple nodes "watching" the same section, you can't really make great guesses as to which node you should be replacing in your front buffer DOM with a node from the back buffer DOM. If it's only ever a 1:1 section key, then it would work. 

I think we also considered tracking it in a simple index like 

** front-buffer DOM **
```javascript
{
  0: [div id="customer_list"]
  1: [div id="customer_bubble"]
  2: [div id="customer_modal"]
}
```

However without some kind of unique identifier (we used `id`), you run in to problems if your page refresh adds or removes something based on the state change of the data

**back-buffer DOM**
```javascript
{
  0: [div id="customer_list"]
  1: [div id="customer_modal"] // how do I know this index 1 is actually index 2 in my front buffer?
}
```

**Comment by dhh** [comment]
Ah, yes, of course. Makes sense. Although I’d expect that the normal case would be that you only have the 1:1? But I guess we need to deal with both.

**Comment by mrkurt** [comment]
This discussion of the future solves a current problem for us. So :+1:

**Comment by kristianpd** [comment]
I'm still planning on getting around to this in a couple weeks, been swamped lately. 

I'm going to take a shot at pulling out the partial refresh stuff from Turbograft and hook it up to a `respond_with` option / controller decision as @dhh had suggested.

**Comment by dhh** [comment]
:metal:

**Comment by obsidienne** [comment]
With this you can keep an audio/video playing between page navigation so :+1:

**Comment by aantix** [comment]
I've been following the conversation and have an alternative idea: there's parity between the view's cached fragments and the sections that need to be updated on an XHR request.

Why not have the (view) cache blocks double as the section definitions?  When an xhr request is made, the page is rendered but only the cache sections that are re-rendered (non-cached) are sent back to the client (a hash of changes).  Some lightweight js can find the prior section and replace it with the new render?  

By having a 'section' definition, the developer gets the initial Russian Doll fragment caching along with defining appropriate sections for client side updates.

I'll do a proof of concept and open a separate PR.

**Comment by kristianpd** [comment]
Yeah, that's a good point @aantix. I had suggested the same to @dhh but the only downside is that now you're coupling the fragment caching to it (maybe not necessarily a downside :)). Two considerations:

1. You'll need some kind of DOM node hook for the current Turbograft refresh strategy to know what to replace. It's possible for nodes to come and go during a partial replace, so we use `id` + `refresh` attributes on the node itself to hook it. You may be able to do something with comment nodes to avoid any possible effect on the DOM structure.

2. You'll need your cache keys to have some predictable prefix on them as the suffix of the key will likely change with each partial update (the data is changing). You may be able to use `action` and `action_suffix` options for this, we don't have this style of caching in our app so I can't really speak to any other gotchas here.


I'm also really interested in seeing if this works, feel free to ping me on PRs. I will likely play around with this at the end of Feb (we have a few hack days coming up), maybe we can bounce a few ideas around before then.

**Comment by aantix** [comment]
Great considerations @kristianpd.  

1) For the initial proof of concept, I was going to just render a div.  Comment nodes look much more promising and less intrusive.  Thanks for the suggestion.

2) I was hoping div_for was smart enough to create a unique, predictable ID for varying dependencies.  It's not the case.  I can probably extract something from the cache helper (I think there's a unique ID generated before the cache digest is computed).

I'll definitely ping you on the PR when it's done.

**Comment by dhh** [comment]
I think the auto-detection is an interesting experiment, but the underlying power to update selectively is still valuable. You won't always be able to follow the automatic inference, and you'll need the lower level API to do it anyway. So I'm most interested in getting the manual building blocks in place first, then trying to level-up on top of that afterwards.

**Comment by Daniel254** [comment]
I just leave it there.
It's similar project with partial rendering

https://github.com/igor-alexandrov/wiselinks

**Comment by ssorallen** [comment]
This is an interesting discussion, and if you take it to the extreme of tracking every DOM node automatically you can get something like what I've put together: https://github.com/ssorallen/turbo-react

turbo-react doesn't modify Turbolinks. It monkeypatches `document.documentElement.replaceChild`, the method Turbolinks calls at the end of the loading process, with a version that turns the HTML into JSX, then uses the JSX parser to convert to React function calls, and then lets React do its DOM diffing and minimal updating. This limits the manual cues needed from the developer and needs no extra help from the server.

The HTML -> JSX -> React combination behaves similar to ideas mentioned above: it tracks DOM nodes with unique IDs (`data-react-id`) and updates only parts of the page that have changed. Node IDs are determined by their path in the tree, which means if their path changes between renders it will not be considered the same node. That's where something like `data-turbolinks-partial` has an advantage: the developer can mark nodes as being the same across renders.

**Comment by dhh** [comment]
Ross, that’s an interesting project. I’m curious as to when it matters to truly flow through react vs just doing these innerHTML replacements. I get it in the actual React case, because the logic is all client-side, so you’re basically just doing a redraw. But in our case, redraw only happens in response to a HTTP request. And in that case, I don’t think innerHTML is the bottleneck. The bottleneck is likely to be the remote operation, and the transfer of the response. 

Happy to be enlightened to otherwise.

I like React because it’s the same motivation as Turbolinks: Avoid client-side state as much as possible! It’s just whether the updates are triggered from client or server.

**Comment by ssorallen** [comment]
@dhh Yup, I don't think innerHTML is a bottleneck, and I didn't mean to imply turbo-react was fixing a bottleneck or any problems in Turbolinks. I added React as an experiment to have finger-grained automatic mutations than `documentElement.replaceChild` to enable things like CSS transitions. The example in the turbo-react README demonstrates a simple case:

css:
```css
.foo { transition: background-color 0.5s; }
.bar { background-color: yellow; }
.baz { background-color: blue; }
```

doc1:

```html
<body>
  <div class="foo bar"></div>
</body>
```

doc2:

```html
<body>
  <div class="foo baz"></div>
</body>
```

Turbolinks replaces the body with the body tag of doc2, but turbo-react finds that the minimum change to get from doc1 to doc2 is actually `div.className = 'foo baz'` (or maybe some use of `classList` if supported). With turbo-react you'll see the background-color transition.

**Comment by dhh** [comment]
Ross, gotcha. That seems perfectly legit for that use case. Thanks for putting it out there.

**Comment by qq99** [comment]
re: @ssorallen 

>I added React as an experiment to have finger-grained automatic mutations than documentElement.replaceChild to enable things like CSS transitions.

That's amazing!  I was just musing the other day that some kind of DOM diffing instead of outright replacements would be the only way for TurboGraft to work well with replacements & CSS transitions without adding some kind of animation lock  (cc @tmlayton)

**Comment by tmlayton** [comment]
re: turbo-react; That is great. @ssorallen any reservations about moving it beyond an experiment?

**Comment by ssorallen** [comment]
@tmlayton I don't want to hijack this thread. Do you want to open an issue on turbo-react to chat? Happy to chat there.
