### ISSUE TITLE
Turbolinks + UJS works together?

### ISSUE THREAD

**Issue by the-teacher** [rails/turbolinks#519]
Hello. I have following simple code

`rails 4.2.1` + `turbolinks (2.5.3)`

```coffee
//= require jquery
//= require jquery_ujs
//= require turbolinks
```

(I haven't any custom JS code)

```slim
doctype html
html
head
  title Dummy App
  = stylesheet_link_tag      :application, 'data-turbolinks-track' => true, media: :all
  = javascript_include_tag :application, 'data-turbolinks-track' => true
  = csrf_meta_tags
body
  .body
     = yield
```
I visited few pages and after I press "submit" button on `remote: true` form. And submit request was executed many times.

It looks like UJS was initialized on each `document.ready` or `page:load`

Can it be bug? or I did somthing wrong?

**Comment by the-teacher** [comment]
looks like my wrong

**Comment by abitdodgy** [comment]
If anyone stumbles across this issue, it happened because the markup was wrong. If you look closely you can see that the `head` and `body` tags are not nested correctly under the `html` tag. This causes Turbolinks to bind a new event on every page change. Just an FYI for those who may stumble on this.

```slim
doctype html
html
head
  title Dummy App
  = stylesheet_link_tag      :application, 'data-turbolinks-track' => true, media: :all
  = javascript_include_tag :application, 'data-turbolinks-track' => true
  = csrf_meta_tags
body
  .body
     = yield
```
