### ISSUE TITLE
assetsChanged() returning true for partial responses 

### ISSUE THREAD

**Issue by stalcottsmith** [rails/turbolinks#522]
I'm trying the new partial page update functionality.

I have something like this:

```ruby
render partial: 'post', change: :sidebar
```

Right now in development mode, it reloads the whole page every time after the first Turbolinks request returns with the partial because assetsChanged() returns true.  The function is looking for assets in the returned document, however, I am only returning a partial, hence, no assets.

If this should be supported, I will contribute a fix.  If I am misunderstanding something please let me know.

**Comment by Thibaut** [comment]
Which library makes the request to the partial endpoint? 

If you let Turbolinks make the request (when clicking a link or by using `Turbolinks.visit`), then the `change` option will be ignored (since Turbolinks requests are not considered XHR in the controller, and the partial replacement options only apply to XHR requests).

This is because all your links (and `visit` URLs) are expected to point to endpoints that render full pages. Otherwise your website would be broken in browsers that don't support Turbolinks, like IE9 and search engine bots (the browser will follow the link/URL and show the partial).

To use partials this way, you need to use jQuery / [jquery-ujs](https://github.com/rails/jquery-ujs) (or send `X-Requested-With: XMLHttpRequest` in your XHRs + automatically execute scripts when the response type is JavaScript).

Otherwise you have to render the full page and manually call `Turbolinks.visit` with a `change` option (normal links don't support partial replacements at the moment).

I'll update the README soon to make this more clear.

**Comment by stalcottsmith** [comment]
Thank you @Thibaut -- I was unclear whether it was okay to distinguish Turbolinks requests from non Turbolinks requests, by for example looking for the params[:_].  Apparently this is not the intention.  In my use case it would be faster to only render the partial as I am displaying both a collection and a resource in the page but I want to stick as close as possible to the intended usage.
