### ISSUE TITLE
Partial change + Update url

### ISSUE THREAD

**Issue by vizo** [rails/turbolinks#532]
I have case to change just part of the page with get method. I also think this case is very common (for example tabs).
Is it possible to call Turbolinks.visit('some_url', {change: 'some_element_id'}) somehow from controller?

If i use remote: true on link_to with controller:
render :some_view, change: "some_element_id"
it cals Turbolinks.replace which doesn't update URL.

Without remote: true it refreshes whole body even if i use "change" in controller.

Did i miss something?

**Comment by Thibaut** [comment]
>  Is it possible to call Turbolinks.visit('some_url', {change: 'some_element_id'}) somehow from controller?

`redirect_to some_url, change: 'some_element_id'` & use `remote: true`.

**Comment by vizo** [comment]
Ok let's say i want to refresh a partial list by pointing link to index action in controller.

So i need to point it first to another action and put there redirect to index action which will render it? Or is there any other way to use just one (same) action?

**Comment by Thibaut** [comment]
You don't need to redirect to another action. Just do `render :index, change: 'list'` and make sure your link is `remote: true`. If you want the URL to be updated, you should capture the click event on the link and call `Turbolinks.visit(url, change: ['list'])` manually.

Partial replacement isn't really meant to speed up navigation. Its primary goal is to let you refresh bits of the same page you're currently looking at, e.g., following a form submission.

If you want to keep state around from page to page, you can do that using `data-turbolinks-permanent`.

**Comment by vizo** [comment]
Thanks for your help. I know how turbolinks works, but i was hoping there is other simpler way to do it. 

Actually this is what i did. I wrote jQuery plugin that finds all elements with attribute data-turbolinkvisit="{change: 'some_element_id'}", binds click event calling 
```javascript
Turbolinks.visit(element.attr('href'), JSON.parse(element.attr('data-turbolinkvisit')); return false;
```
It would be nice to have this helper out of the box.

P.S. Your scroll solution works perfectly, navigation trough page looks like on SPA.

Just one more question. Progress bar is showing by clicking on all links, but if you set param method: :get on link_to, it doesn't show. Do you have any idea why?

**Comment by Thibaut** [comment]
> It would be nice to have this helper out of the box.

This has come up a couple times. I'll likely PR a similar helper soon. Thanks for the feedback.

**Comment by ginolon** [comment]
I need somthing like this in a page with two columns:

MENU AREA     |     ITEMS AREA
                         |
                         |
                         |

How to accomplish this?

Using this (http://railscasts.com/episodes/246-ajax-history-state) cast, I fix my problem, but with Turbolinks 3 (I love it!) I can't use that code (i mentioned also in: https://github.com/rails/turbolinks/issues/542) because you said to me it's wrong code.

Question:

With the code in railscast my application is too fast, with turbolinks (visit, replace, remote:true and everything I tried) the page is reloaded every time in background (so, the menu is reloaded every time, with many queries to the database and the singole div "ITEMS AREA" is updated.

WHAT I need is a system like that code (that works unless onpopstate event that doesn't work with Turbolinks) that allow me to update (and not regenerate in background!!!) just a REAL partial of the page.

Is that possible with Turbolinks's methods?

**Comment by ginolon** [comment]
@vizo Do you know the n° 246 Railscast?
