### ISSUE TITLE
How to detect if the request is a turbolinks request

### ISSUE THREAD

**Issue by phlegx** [rails/turbolinks#634]
Hi!

How can I detect on the controller if the request is a turbolinks request? Any idea?

Thx

**Comment by Thibaut** [comment]
There is currently no way to detect Turbolinks requests server-side. This is intentional — for simplicity (no `if request.turbolinks?` all over your codebase), and because Turbolinks needs the entire page to be rendered to work properly (to track assets, update CSRF tokens, update `<title>`, etc.)

**Comment by inopinatus** [comment]
When Turbolinks is fetching a page for replacement via AJAX, it sets the X-XHR-Referer header. I've use this server-side as a hint that "turbolinks was probably used", to tune the UX of a particular form.

Upside: it is the common case and good enough for tuning UI behaviour.

Downsides: undocumented; other components could set it; sometimes turbolinks will fallback and fetch a page by built-in navigation rather than an AJAX call, in which case the header is not set. Cannot be relied upon for general behaviour.

Hence:
``` ruby
  def its_probably_turbolinks
    request.headers["X-XHR-Referer"].present?
  end
```

**Comment by grosser** [comment]
this seems to work: `request.env["HTTP_TURBOLINKS_REFERRER"]`

**Comment by inopinatus** [comment]
@grosser Are you looking at Turbolinks 5? That header is not set in turbolinks-classic.

**Comment by grosser** [comment]
5

**Comment by inopinatus** [comment]
For those who visit this thread later, please note, this is not the Turbolinks 5 repository. For turbolinks 2.5, `request.headers["X-XHR-Referer"]` remains the best available way.
